on: push
jobs:
  mvn-verify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - run: mvn verify